`PuDBWrapper#pytest_exception_interact`: Remove call to `self.disable_io_capture()`
It is not needed, since the calling chain:
- `_enter_pudb`
- `post_mortem`
- `pudb._get_debugger()`

will still call `PuDBWrapper#_get_debugger`, which also calls `self.disable_io_capture()`

Avoids the double-prologue:

```console
$ pytest -x --pudb
======================================= test session starts ========================================
platform linux -- Python 3.9.16, pytest-7.2.1, pluggy-1.0.0
rootdir: .., configfile: pyproject.toml
plugins: pycharm-0.7.0, pudb-0.7.0, dash-2.8.1, cov-4.0.0
collected 1726 items

../tests/test_parsers.py F
>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PuDB (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PuDB (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

===================================== short test summary info ======================================
FAILED ../tests/test_parsers.py::test_parse[..] - KeyError: "None of ['taskID'] are in the columns"
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================== 1 failed in 2.48s =========================================
```

vs

```console
$ pytest -x --pudb
======================================= test session starts ========================================
platform linux -- Python 3.9.16, pytest-7.2.1, pluggy-1.0.0
rootdir: .., configfile: pyproject.toml
plugins: pycharm-0.7.0, pudb-0.7.0, dash-2.8.1, cov-4.0.0
collected 1726 items

../tests/test_parsers.py F
>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PuDB (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

===================================== short test summary info ======================================
FAILED ../tests/test_parsers.py::test_parse[..] - KeyError: "None of ['taskID'] are in the columns"
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================== 1 failed in 3.62s =========================================
```

Cannot do the opposite thing, since then `pu.db` and friends
will loose the opportunity to do prologue
(`pytest_exception_interact` is called only via the `--pudb` flag)

Additionally, update `.gitignore`
(via https://github.com/github/gitignore/commit/8e67b9420cb6796e5eeca72682babdb06627ec8c)

Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>